Get-Childitem -Directory | Select-Object Name | foreach {cd $_.Name; 
$fixedText = ''
$fixedText = Get-Content -path Strukturmodell.graphml -Raw
$fixedText = $fixedText -replace '<y:', '<'
$fixedText = $fixedText -replace '</y:', '</'
$fixedText = $fixedText -replace '\s*</?(ImageNode|PreferredPlacementDescriptor|SmartEdgeLabelModelParameter|SmartEdgeLabelModel|EdgeLabel|Point|Resources|key|graphml|Shape|BorderStyle|data|Geometry|SmartNodeLabelModel|ModelParameter|PolyLineEdge|Path|Arrows|BendStyle|LabelModel|SmartNodeLabelModel)[^>]*>', ''
$fixedText = $fixedText -replace '\s(type|edgedefault|transparent|alignment|autoSizePolicy|fontFamily|fontSize|fontStyle|hasBackgroundColor|hasLineColor|height|horizontalTextPosition|iconTextGap|modelName|textColor|verticalTextPosition|visible|width|x|xml:space|y)="[^"]*"', ''
$fixedText = $fixedText -replace 'hasColor="false"', 'color="#FFFFFF"'
$fixedText = $fixedText -replace '\n', ''
$fixedText = $fixedText -replace ':\r', ': '
$fixedText = $fixedText -replace 'A\r', 'A '
$fixedText = $fixedText -replace 'a\r', 'a '
$fixedText = $fixedText -replace 'b\r', 'b '
$fixedText = $fixedText -replace 'c\r', 'c '
$fixedText = $fixedText -replace 'd\r', 'd '
$fixedText = $fixedText -replace 'e\r', 'e '
$fixedText = $fixedText -replace 'f\r', 'f '
$fixedText = $fixedText -replace 'g\r', 'g '
$fixedText = $fixedText -replace 'h\r', 'h '
$fixedText = $fixedText -replace 'i\r', 'i '
$fixedText = $fixedText -replace 'j\r', 'j '
$fixedText = $fixedText -replace 'k\r', 'k '
$fixedText = $fixedText -replace 'l\r', 'l '
$fixedText = $fixedText -replace 'm\r', 'm '
$fixedText = $fixedText -replace 'n\r', 'n '
$fixedText = $fixedText -replace 'o\r', 'o '
$fixedText = $fixedText -replace 'p\r', 'p '
$fixedText = $fixedText -replace 'q\r', 'q '
$fixedText = $fixedText -replace 'r\r', 'r '
$fixedText = $fixedText -replace 's\r', 's '
$fixedText = $fixedText -replace 't\r', 't '
$fixedText = $fixedText -replace 'u\r', 'u '
$fixedText = $fixedText -replace 'v\r', 'v '
$fixedText = $fixedText -replace 'w\r', 'w '
$fixedText = $fixedText -replace 'x\r', 'x '
$fixedText = $fixedText -replace 'y\r', 'y '
$fixedText = $fixedText -replace 'z\r', 'z '
$fixedText = $fixedText -replace '</graph>[\w|\W|\r|\n]*', '</graph>'
$fixedText = $fixedText -replace '<node id="[^<]*<Fill[^<]*<NodeLabel[^<]*<Image[^<]*</node>', ''
$fixedText = $fixedText -replace '(\s+)$', ''
$fixedText | Set-Content -Path Strukturmodell_Cleaned.txt
cd ..
}